# https://docs.travis-ci.com/user/languages/go
language: go
sudo: false
go:
  - 1.11.x
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - GO111MODULE=on
  - DATABASE_URL="postgres://postgres@localhost/travis_ci_test?sslmode=disable"
script:
  - go vet ./...
  - go build .
  - go test -v
notifications:
  email:
    on_success: change
    on_failure: change
