# https://docs.travis-ci.com/user/languages/go
language: go
sudo: false
addons:
  postgresql: 9.6
go:
  - 1.11.x
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
    - GO111MODULE=on
    - DATABASE_URL="postgres://postgres@localhost/travis_ci_test?sslmode=disable"
script:
  - go vet ./...
  - go build -o ./server.out ./server
  - go test -v ./...
notifications:
  email:
    on_success: change
    on_failure: change
