# https://docs.travis-ci.com/user/languages/go
language: go
go:
  - "1.16"
addons:
  postgresql: 9.6
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
    - GO111MODULE=on
    - DATABASE_URL="postgres://postgres@localhost/travis_ci_test?sslmode=disable"
script:
  - go test -v -cover ./...
  - go vet ./...
  - go get -v -u -d golang.org/x/lint/golint
  - go run golang.org/x/lint/golint -set_exit_status ./...
  - go get -v -u -d github.com/fzipp/gocyclo/cmd/gocyclo
  - go run github.com/fzipp/gocyclo/cmd/gocyclo -avg .
notifications:
  email:
    on_success: change
    on_failure: change
