# https://docs.travis-ci.com/user/languages/go
language: go
sudo: false
go:
  - 1.11.x
env:
  - GO111MODULE=on
script:
  - go vet ./...
  - go build .
  - go test -v
notifications:
  email:
    on_success: change
    on_failure: change
